/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uas;

/**
 *
 * @author NICHOLAS
 */
public class Main_Head extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main_Head.class.getName());

    /**
     * Creates new form Main_Head
     */
    
    private int userId;
    private String username;
    private String role;

    public Main_Head(int userId, String username, String role) {
        this.userId = userId;
        this.username = username;
        this.role = role;

        initComponents();
        Header.setText("Head - Index | " + username);
    }

    public Main_Head(String username) {
        this(0, username, "SUPERVISOR");
    }

    public Main_Head() {
        this(0, null, "SUPERVISOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        produk = new javax.swing.JButton();
        user = new javax.swing.JButton();
        stok = new javax.swing.JButton();
        inbound = new javax.swing.JButton();
        outbound = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Header.setText("Head - Index");

        produk.setText("Produk");
        produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkMouseClicked(evt);
            }
        });

        user.setText("User");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });

        stok.setText("Stok");
        stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokMouseClicked(evt);
            }
        });

        inbound.setText("Inbound");
        inbound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboundMouseClicked(evt);
            }
        });

        outbound.setText("Outbound");
        outbound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outboundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inbound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outbound))
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(produk)
                    .addComponent(stok)
                    .addComponent(inbound)
                    .addComponent(outbound))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Produk indexP = new Main_Produk(username);
        indexP.setVisible(true);
    }//GEN-LAST:event_produkMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Main_User users = new Main_User(username);
        users.setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Stok stock = new Main_Stok(userId, username, role);
        stock.setVisible(true);
    }//GEN-LAST:event_stokMouseClicked

    private void inboundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboundMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Inbound inb = new Inbound(userId, username, role);
        inb.setVisible(true);
    }//GEN-LAST:event_inboundMouseClicked

    private void outboundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outboundMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Outbound out = new Outbound(userId, username, role);
        out.setVisible(true);
    }//GEN-LAST:event_outboundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main_Head().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JButton inbound;
    private javax.swing.JButton outbound;
    private javax.swing.JButton produk;
    private javax.swing.JButton stok;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
