/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uas;

/**
 *
 * @author NICHOLAS
 */
public class Main_Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main_Admin.class.getName());

    /**
     * Creates new form Main_Admin
     */
    
    private int userId;
    private String username;
    private String role;

    public Main_Admin(int userId, String username, String role) {
        this.userId = userId;
        this.username = username;
        this.role = role;

        initComponents();
        jLabel1.setText("Admin - Index | " + username);
    }

    public Main_Admin(int userId, String username) {
        this(userId, username, "ADMIN");
    }

    public Main_Admin() {
        this(0, "Admin", "ADMIN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Inbound = new javax.swing.JButton();
        stok = new javax.swing.JButton();
        Outbound = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin - Index");

        Inbound.setText("Inbound");
        Inbound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InboundMouseClicked(evt);
            }
        });

        stok.setText("Stok");
        stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokMouseClicked(evt);
            }
        });

        Outbound.setText("Outbound");
        Outbound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutboundMouseClicked(evt);
            }
        });
        Outbound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutboundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Inbound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Outbound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stok)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inbound)
                    .addComponent(stok)
                    .addComponent(Outbound))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Stok stock = new Main_Stok(userId, username, role);
        stock.setVisible(true);
    }//GEN-LAST:event_stokMouseClicked

    private void OutboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutboundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutboundActionPerformed

    private void OutboundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutboundMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Outbound out = new Outbound(userId, username, role);
        out.setVisible(true);
    }//GEN-LAST:event_OutboundMouseClicked

    private void InboundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InboundMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Inbound inb = new Inbound(userId, username, role);
        inb.setVisible(true);
    }//GEN-LAST:event_InboundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main_Admin(0, "TEST").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inbound;
    private javax.swing.JButton Outbound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton stok;
    // End of variables declaration//GEN-END:variables
}
