/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uas;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author NICHOLAS
 */
public class Surat_Jalan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Surat_Jalan.class.getName());

    private int trxId;
    private int userId;

    public Surat_Jalan(int trxId, String noSuratJalan, int userId, String buyerName) {
        this.trxId = trxId;
        this.userId = userId;

        initComponents();
        setupForm(noSuratJalan, buyerName);
        setupEvents();
    }
    
    private void setupForm(String noSuratJalan, String buyerName) {
        setLocationRelativeTo(null);

        no_sj.setText(noSuratJalan);
        no_sj.setEditable(false);
        
        np.setText(buyerName);
    }
    
    private void setupEvents() {
        save.addActionListener(e -> saveSuratJalan());
    }
    
    private void saveSuratJalan() {
        String nama = np.getText().trim();
        String alamat = ap.getText().trim();
        String hp = phone.getText().trim();
        String catatan = notes.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama penerima wajib diisi!");
            return;
        }
        if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat wajib diisi!");
            return;
        }
        if (hp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No HP wajib diisi!");
            return;
        }

        Connection conn = null;
        PreparedStatement ps = null;

        try {
            conn = Koneksi.getConnection();

            String sql = """
                INSERT INTO surat_jalan
                (trx_id, sj_no, recipient_name, recipient_address, recipient_phone, notes, created_by, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, NOW())
            """;

            ps = conn.prepareStatement(sql);
            ps.setInt(1, trxId);
            ps.setString(2, no_sj.getText());
            ps.setString(3, nama);
            ps.setString(4, alamat);
            ps.setString(5, hp);
            ps.setString(6, catatan);
            ps.setInt(7, userId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Surat jalan berhasil disimpan!\nNo: " + no_sj.getText());

            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal simpan surat jalan:\n" + ex.getMessage());
        } finally {
            try { if (ps != null) ps.close(); } catch (Exception ignored) {}
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        no_sj = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        np = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        ap = new javax.swing.JTextField();
        nohp = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        ctt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        head.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        head.setText("Surat Jalan");

        no.setText("No Surat Jalan");

        nama.setText("Nama Penerima");

        alamat.setText("Alamat Penerima");

        nohp.setText("No Handphone");

        ctt.setText("Catatan");

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        save.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no)
                            .addComponent(nama)
                            .addComponent(alamat)
                            .addComponent(nohp)
                            .addComponent(ctt))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(np, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(no_sj)
                            .addComponent(ap, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no)
                    .addComponent(no_sj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nohp)
                        .addGap(18, 18, 18)
                        .addComponent(ctt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField ap;
    private javax.swing.JLabel ctt;
    private javax.swing.JLabel head;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel no;
    private javax.swing.JTextField no_sj;
    private javax.swing.JLabel nohp;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField np;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
